export const PROV_RENAME_MAP = {
  "IRIAN JAYA TIMUR": "Papua",
  "IRIAN JAYA BARAT": "Papua Barat",
  "IRIAN JAYA TENGAH": "Papua Tengah",
  "IRIAN JAYA SELATAN": "Papua Selatan",
  "IRIAN JAYA PEGUNUNGAN": "Papua Pegunungan",
  "NUSATENGGARA BARAT": "Nusa Tenggara Barat",
  "NUSATENGGARA TIMUR": "Nusa Tenggara Timur",
  "KALIMANTAN SELATAN": "Kalimantan Selatan",
  "KALIMANTAN TIMUR": "Kalimantan Timur",
  "KALIMANTAN TENGAH": "Kalimantan Tengah",
  "KALIMANTAN BARAT": "Kalimantan Barat",
  "KALIMANTAN UTARA": "Kalimantan Utara",
  "SULAWESI SELATAN": "Sulawesi Selatan",
  "SULAWESI TENGGARA": "Sulawesi Tenggara",
  "SULAWESI TENGAH": "Sulawesi Tengah",
  "SULAWESI BARAT": "Sulawesi Barat",
  "SULAWESI UTARA": "Sulawesi Utara",
  "SUMATERA UTARA": "Sumatera Utara",
  "SUMATERA BARAT": "Sumatera Barat",
  "SUMATERA SELATAN": "Sumatera Selatan",
  "KEPULAUAN RIAU": "Kepulauan Riau",
  "RIAU": "Riau",
  "BENGKULU": "Bengkulu",
  "JAMBI": "Jambi",
  "LAMPUNG": "Lampung",
  "BANGKA BELITUNG": "Bangka Belitung",
  "JAWA BARAT": "Jawa Barat",
  "JAWA TENGAH": "Jawa Tengah",
  "JAWA TIMUR": "Jawa Timur",
  "BANTEN": "Banten",
  "BALI": "Bali",
  "DKI JAKARTA": "DKI Jakarta",
  "DI YOGYAKARTA": "DI Yogyakarta",
  "DI. ACEH": "Aceh",
  "GORONTALO": "Gorontalo",
  "MALUKU": "Maluku",
  "MALUKU UTARA": "Maluku Utara",
};
